### ISSUE TITLE
Is Visual Studio Proffessional not supported?

### ISSUE THREAD

**Issue by Sti2nd** [waf/RunOnSave#3]
Hi,
When I try to install the extension I get the following error

<details>

```text
22/11/2021 14:50:53 - Microsoft VSIX Installer
22/11/2021 14:50:53 - -------------------------------------------
22/11/2021 14:50:53 - vsixinstaller.exe version:
22/11/2021 14:50:53 - 16.11.12
22/11/2021 14:50:53 - -------------------------------------------
22/11/2021 14:50:53 - Command line parameters:
22/11/2021 14:50:53 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\JORSTI\Downloads\RunOnSave.vsix
22/11/2021 14:50:53 - -------------------------------------------
22/11/2021 14:50:53 - Microsoft VSIX Installer
22/11/2021 14:50:53 - -------------------------------------------
22/11/2021 14:50:54 - Skipping product Microsoft.VisualStudio.Product.BuildTools (2478a8f1) since it does not support extensions
22/11/2021 14:50:54 - Initializing Install...
22/11/2021 14:50:54 - Extension Details...
22/11/2021 14:50:54 - 	Identifier         : RunOnSave.7de8e627-4e33-4425-84ba-cc028ada1ca0
22/11/2021 14:50:54 - 	Name               : RunOnSave
22/11/2021 14:50:54 - 	Author             : Will Fuqua
22/11/2021 14:50:54 - 	Version            : 1.1
22/11/2021 14:50:54 - 	Description        : A Visual Studio extension that can run commands on files when they're saved. Configured using an .onsaveconfig file, which can be checked into version control.
22/11/2021 14:50:54 - 	Locale             : en-US
22/11/2021 14:50:54 - 	MoreInfoURL        : https://github.com/waf/RunOnSave/
22/11/2021 14:50:54 - 	InstalledByMSI     : False
22/11/2021 14:50:54 - 	SupportedFrameworkVersionRange : [4.5,)
22/11/2021 14:50:54 - 
22/11/2021 14:50:54 - 	SignatureState     : Unsigned
22/11/2021 14:50:54 - 	Supported Products : 
22/11/2021 14:50:54 - 		Microsoft.VisualStudio.Community
22/11/2021 14:50:54 - 			Version : [17.0,18.0)
22/11/2021 14:50:54 - 		Microsoft.VisualStudio.Community
22/11/2021 14:50:54 - 			Version : [16.0]
22/11/2021 14:50:54 - 		Microsoft.VisualStudio.Pro
22/11/2021 14:50:54 - 			Version : [17.0,18.0)
22/11/2021 14:50:54 - 		Microsoft.VisualStudio.Pro
22/11/2021 14:50:54 - 			Version : [16.0]
22/11/2021 14:50:54 - 		Microsoft.VisualStudio.Enterprise
22/11/2021 14:50:54 - 			Version : [17.0,18.0)
22/11/2021 14:50:54 - 		Microsoft.VisualStudio.Enterprise
22/11/2021 14:50:54 - 			Version : [16.0]
22/11/2021 14:50:54 - 
22/11/2021 14:50:54 - 	References         : 
22/11/2021 14:50:54 - 	Prerequisites      : 
22/11/2021 14:50:54 - 		-------------------------------------------------------
22/11/2021 14:50:54 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
22/11/2021 14:50:54 - 		Name         : Visual Studio core editor
22/11/2021 14:50:54 - 		Version      : [17.0,18.0)
22/11/2021 14:50:54 - 
22/11/2021 14:50:54 - Signature Details...
22/11/2021 14:50:54 - 	Extension is not signed.
22/11/2021 14:50:54 - 
22/11/2021 14:50:54 - Searching for applicable products...
22/11/2021 14:50:54 - Found installed product - Global Location
22/11/2021 14:50:54 - Found installed product - Visual Studio Professional 2019 (2)
22/11/2021 14:50:54 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
</details>

I am on Visual Studio Professional 2019, Version 16.11.7. 
The reason it is parenthesis 2 `(2)` at the end is simply because I had another VS installed before and Windows added the parethesis to differ between them.

**Comment by Sti2nd** [comment]
Seems like I can install it in VS Professional 2022.

**Comment by waf** [comment]
Hi, thanks for raising this issue. You're right, VS2019 is not supported, and all versions of VS 2022 are supported. That's mostly just because the extension itself was developed with VS2022, so VS2019 support was never implemented.

I notice that the Visual Studio Marketplace lists it as as compatible with VS2019, though, so that's confusing.

Looks straightforward to support VS2019; just some config file changes. I'll take a look. Cheers!

**Comment by waf** [comment]
Done, the extension (version 1.2) is now compatible with both VS2019 and VS2022, all versions. Thanks for pointing this out.

**Comment by Sti2nd** [comment]
Thank you for fixing it! 🏆
